Command_Rafał Koliński_206057
iis-powp-2019z-pwhd-backup/powp_jobs2d_project pull request #31
Opened 2019-11-19 22:00 UTC by RafalKolin

2019-11-24 16:18 UTC, LordIllidan requested changes
Wymagana poprawa Adaptera
Command jest OK

2019-11-24 16:18 UTC, LordIllidan commented on src/main/java/edu/kis/powp/jobs2d/command/DriverCommand.java
> +    void addCommand(DriverCommand driverCommand);
Skoro nie implementujemy tej metody w większości klas - sugerowałbym jej nie trzymać w tym interfejsie

2019-11-24 16:18 UTC, LordIllidan commented on src/main/java/edu/kis/powp/jobs2d/command/ComplexCommand.java
> +    public void execute(Job2dDriver driver) {
Można było przez konstruktor przekazać też tablice

2019-11-24 16:18 UTC, LordIllidan commented on src/main/java/edu/kis/powp/jobs2d/command/SetPossitionCommand.java
> +    public void addCommand(DriverCommand driverCommand) {
Jak powyżej

2019-11-24 16:18 UTC, LordIllidan commented on src/main/java/edu/kis/powp/jobs2d/command/factory/CircleDrawer.java
> +        complexCommand.addCommand(new SetPossitionCommand(radius, 0));
co się stanie jak wywołam ta metodę kilka razy ?

2019-11-24 16:18 UTC, LordIllidan commented on src/main/java/edu/kis/powp/jobs2d/command/factory/RectangleDrawer.java
> +        complexCommand.addCommand(new SetPossitionCommand( -100, -100));
jak powyżej

2019-11-24 16:18 UTC, LordIllidan commented on src/main/java/edu/kis/powp/jobs2d/command/factory/TriangleDrawer.java
> +        complexCommand.addCommand(new SetPossitionCommand(100, 100));
Jak powyżej

2019-11-24 16:18 UTC, LordIllidan commented on src/main/java/edu/kis/powp/jobs2d/drivers/adapter/AdapterDrawer.java
> +		DrawerFeature.getDrawerController().drawLine(line);
Dlaczego pobiera Pan Drawer Controller skoro adapter też jest DrawerControllerem

2019-11-24 16:18 UTC, LordIllidan commented on src/main/java/edu/kis/powp/jobs2d/drivers/adapter/AdapterDrawer.java
> +		DrawerFeature.getDrawerController().drawLine(line);
Niech zwróci Pan uwagę na diagram klas w zadaniu

2019-12-01 14:20 UTC, RafalKolin commented on src/main/java/edu/kis/powp/jobs2d/drivers/adapter/AdapterDrawer.java
> +		DrawerFeature.getDrawerController().drawLine(line);
Niepotrzebnie rozszerzałem klasę "AdapterDrawer". Zmiany zostały zaktualizowane.

2019-12-14 18:13 UTC, LordIllidan commented
Zaliczone 3,5

2019-12-14 18:13 UTC, closed without merging