Pull request Adam Domański
iis-powp-2019z-pwhd-backup/powp_jobs2d_project pull request #7
Opened 2019-10-27 15:12 UTC by adann96

2019-11-03 17:50 UTC, LordIllidan reviewed
Na ten moment nie mogę zaliczyć jeszcze adaptera jak i commanda - prośba o wykonanie poprawek i dokończenie zadań

2019-11-03 17:50 UTC, LordIllidan commented on src/main/java/edu/kis/powp/jobs2d/drivers/adapter/drawPanelControllerAdapter.java
>  	private int startX = 0, startY = 0;
Nazwa klasy z małej litery?

2019-11-07 11:46 UTC, kowallus reviewed
Adapter barely started. More tasks are required to get a grade.

2019-11-07 11:46 UTC, kowallus commented on .idea/compiler.xml
> +<project version="4">
Commits polluted with project files

2019-11-07 11:57 UTC, kowallus requested changes
Ustawiam flagę - prośba o poprawki!

2020-01-19 10:35 UTC, LordIllidan reviewed
Odchaczam na 3 zarówno adapter jak i command

2020-01-19 10:35 UTC, LordIllidan commented on src/test/java/edu/kis/powp/legacy/drawer/TestDrawer.java
> +//
Nie zostawiamy za komentowanego kodu

2020-01-19 10:35 UTC, closed without merging